name: CI

on: [ push, pull_request ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
        node: [ '10', '12', '14' ]
    name: Unit Tests Node ${{ matrix.node }} (${{ matrix.platform }})
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: check GITHUB_TOKEN length
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: echo "${#GITHUB_TOKEN}"
      - name: install dependencies
        run: npm ci
      - name: lint + units tests + prepare coveralls
        run: npm run test:ci
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}